### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vigneshshanmugam** [vigneshshanmugam/cdn-finder#2]
- [x] Better Error Handling
- [ ] Get all CDN's details used in a domain. 
- [ ] Third party script calls
